import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faMugHot } from '@fortawesome/free-solid-svg-icons';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<header className='mb-16'>
					<div className='flex justify-between max-w-2xl px-4 py-4 mx-auto'>
						<Link
							className='inline-flex items-center gap-1'
							href={'/'}
						>
							<FontAwesomeIcon
								className='h-8'
								icon={faMugHot}
							/>
							<span className='mt-2'>Buy me a coffe</span>
						</Link>
						<nav className='mt-2 flex gap-6 items-center'>
							<Link href={'/about'}>About </Link>
							<Link href={'/about'}>FAQ </Link>
							<Link href={'/about'}>Contact </Link>

							<div className='flex gap-4'>
								<button className='border-2 rounded-full px-4 py-2 ml-4'>Login</button>
								<button className='bg-yellow-300 rounded-full px-4 py-2'>Sign up</button>
							</div>


						</nav>
					</div>
				</header>

				{children}
			</body>
		</html>
	);
}
